name: Upload to the server

on:
  push:
    branches: [ main ]
      
jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Deploy 
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with: 
          username: ${{secrets.user}}
          server: ${{secrets.ip}}
          ssh_private_key: "${{secrets.ssh_key}}"
          remote_path: '/var/www/html'
          local_path: '.'
